### ISSUE TITLE
[cppbindings] External application build fails if WTF_PTHREAD_THREADED is not defined

### ISSUE THREAD

**Issue by vertexodessa** [google/tracing-framework#583]
The failure is undefined reference to "PlatformGetThreadLocalEventBuffer".

It is inlined in pthreads platform header (https://github.com/google/tracing-framework/blob/master/bindings/cpp/include/wtf/platform/platform_aux_pthreads_threaded_inl.h#L42) which is only included in case WTF_PTHREAD_THREADED is defined:
https://github.com/google/tracing-framework/blob/master/bindings/cpp/include/wtf/platform.h#L52

Could you please clarify whether defining WTF_PTHREAD_THREADED is required while building external application (in this case it would be nice to document it somewhere)..

Thanks!

**Comment by stellaeof** [comment]
I don't have the source on this device to check but I believe you are right
with respect to needing that define. I think that if no threading macro is
defined, it just tries to use the std c++ library for threading -- but that
has varying levels of support, even on platforms that otherwise support
c++11.

I'll add some documentation about how to integrate it into other projects.
Tbh, the makefile was just written to allow us to build it standalone
outside of our build environment, so it has not gotten a ton of love.

On Feb 12, 2017 11:39 AM, "Ihor Ivlev" <notifications@github.com> wrote:

The failure is undefined reference to "PlatformGetThreadLocalEventBuffer".

It is inlined in pthreads platform header (https://github.com/google/
tracing-framework/blob/master/bindings/cpp/include/wtf/
platform/platform_aux_pthreads_threaded_inl.h#L42) which is only included
in case WTF_PTHREAD_THREADED is defined:
https://github.com/google/tracing-framework/blob/master/
bindings/cpp/include/wtf/platform.h#L52

Could you please clarify whether defining WTF_PTHREAD_THREADED is required
while building external application (in this case it would be nice to
document it somewhere)..

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/tracing-framework/issues/583>, or mute the thread

**Comment by vertexodessa** [comment]
I finally could figure out the confusing part, in Makefile THREADING defaults to pthreads:
https://github.com/google/tracing-framework/blob/master/bindings/cpp/Makefile#L19
however in platform.h THREADING defaults to std:
https://github.com/google/tracing-framework/blob/master/bindings/cpp/include/wtf/platform.h#L52

**Comment by stellaeof** [comment]
I've just pushed some updates to the README and Makefile that address this issue. The default threading library is "std" and the Makefile was confusing because it defaulted to "pthread" (this has been a moving target over the life of this library). Afaik, the only popular platform which needs "pthread" instead of "std" is Android. This has been called out in both the Makefile and README. If that doesn't apply to you, then there should be no additional settings or compile time defines needed.
